/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */


@class DVTAnnotationContext, NSMutableArray;

@interface DVTAnnotationManager : NSObject
{
	NSMutableArray *_annotationProviders;
	DVTAnnotationContext *_context;
}

@property(retain) DVTAnnotationContext *context; // @synthesize context=_context;
@property(retain) NSMutableArray *annotationProviders; // @synthesize annotationProviders=_annotationProviders;
- (void)removeAllAnnotationProviders;
- (void)setupAnnotationProvidersWithContext:(id)arg1;
- (id)_installObservationBlockForAnnotationProvider:(id)arg1;

@end
