/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

@class DVTTextFold;
@protocol DVTFoldingManagerDelegate;

@interface DVTFoldingManager : NSObject
{
	DVTTextFold *_topLevelFold;
	id <DVTFoldingManagerDelegate> delegate;
}

@property(retain, nonatomic) DVTTextFold *topLevelFold; // @synthesize topLevelFold=_topLevelFold;
@property __weak id <DVTFoldingManagerDelegate> delegate; // @synthesize delegate;
- (id)adjustFoldsForRange:(struct _NSRange)arg1 changeInLength:(long long)arg2;
- (id)foldsEnclosingRange:(struct _NSRange)arg1;
- (id)lastFoldTouchingCharacterIndex:(unsigned long long)arg1;
- (id)firstFoldTouchingCharacterIndex:(unsigned long long)arg1;
- (id)blockFoldsTouchingRange:(struct _NSRange)arg1;
- (id)allFoldsTouchingRange:(struct _NSRange)arg1;
- (BOOL)isRangeInsideAFold:(struct _NSRange)arg1;
- (BOOL)isCharacterRangeFolded:(struct _NSRange)arg1;
- (BOOL)containsFoldWithRange:(struct _NSRange)arg1;
- (BOOL)isCharacterFoldedAtIndex:(unsigned long long)arg1;
- (void)foldRecursiveItem:(id)arg1;
- (void)unfoldItems:(id)arg1;
- (void)foldItems:(id)arg1;
- (void)unfoldRecursiveRange:(struct _NSRange)arg1;
- (void)unfoldEnclosingRange:(struct _NSRange)arg1;
- (void)unfoldRange:(struct _NSRange)arg1;
- (void)unfoldAtCharacterIndex:(unsigned long long)arg1;
- (void)unfoldAll;
- (void)unfoldPlaceholdersInRange:(struct _NSRange)arg1;
- (void)foldPlaceholderInRange:(struct _NSRange)arg1 withLabel:(id)arg2;
- (void)foldRange:(struct _NSRange)arg1;
- (void)_applyFoldsRecursively:(id)arg1;
- (id)initWithRange:(struct _NSRange)arg1;
- (id)init;

@end

@protocol DVTFoldingManagerDelegate <NSObject>
- (void)foldingManager:(id)arg1 didUnfoldRange:(struct _NSRange)arg2;
- (void)foldingManager:(id)arg1 didFoldRange:(struct _NSRange)arg2;
@end
