/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "DVTMessageBubbleAnnotation.h"

@interface IDEBuildIssueAnnotation : DVTMessageBubbleAnnotation
{
}

+ (BOOL)scrollbarMarkerHighlight;
+ (BOOL)wantsScrollbarMarker;
+ (id)editedTheme;
+ (id)focusedTheme;
+ (id)normalTheme;
+ (id)sidebarIcon;
+ (unsigned long long)severity;
+ (double)precedence;
- (id)init;
- (id)annotationDisplayDescription;
- (id)annotationDisplayName;

@end
