/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "DVTCompletingTextViewDelegate-Protocol.h"

@protocol DVTSourceTextViewDelegate <DVTCompletingTextViewDelegate>

@optional
- (id)textViewWillReturnPrintJobTitle:(id)arg1;
- (void)textViewDidScroll:(id)arg1;
- (void)setupGutterContextMenuWithMenu:(id)arg1;
- (void)tokenizableItemsForItemAtRange:(struct _NSRange)arg1 completionBlock:(id)arg2;
- (void)textViewDidFinishAnimatingScroll:(id)arg1;
- (void)textViewDidLoadAnnotationProviders:(id)arg1;
- (void)textView:(id)arg1 didRemoveAnnotations:(id)arg2;
- (void)textView:(id)arg1 didAddAnnotations:(id)arg2;
- (id)annotationContextForTextView:(id)arg1;
- (id)syntaxColoringContextForTextView:(id)arg1;
- (void)textViewDidChangeFolding:(id)arg1;
- (void)textViewWillChangeFolding:(id)arg1;
- (void)textView:(id)arg1 didClickOnTemporaryLinkAtCharacterIndex:(unsigned long long)arg2 event:(id)arg3 isAltEvent:(BOOL)arg4;
- (BOOL)textView:(id)arg1 shouldShowTemporaryLinkForCharacterAtIndex:(unsigned long long)arg2 proposedRange:(struct _NSRange)arg3 effectiveRanges:(id *)arg4;
- (void)textView:(id)arg1 handleMouseDidExitSidebar:(id)arg2;
- (void)textView:(id)arg1 handleMouseDidMoveOverSidebar:(id)arg2 atLineNumber:(unsigned long long)arg3;
- (void)textView:(id)arg1 handleMouseDownInSidebar:(id)arg2 atLineNumber:(unsigned long long)arg3;
@end

