/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import <Cocoa/Cocoa.h>

@protocol DVTSourceTextScrollViewDelegate <NSObject>

@optional
- (id)scrollView:(id)arg1 pointInVisibleScroller:(struct CGPoint)arg2;
- (void)scrollViewDidSetFrameSize:(id)arg1;
- (void)scrollViewDidEndLiveResize:(id)arg1;
- (void)scrollViewWillStartLiveResize:(id)arg1;
- (void)scrollView:(id)arg1 didReceiveScrollWheelEvent:(id)arg2;
@end

